/*
 * Cloud Hypervisor API
 *
 * Local HTTP based API for managing and inspecting a cloud-hypervisor virtual machine.
 *
 * API version: 0.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// VmRestoreConfig struct for VmRestoreConfig
type VmRestoreConfig struct {
	SourceUrl string `json:"source_url,omitempty"`
}
